spring.application.name=vinsight-api
server.port=8080

# === Banco MySQL ===
spring.datasource.url=jdbc:mysql://localhost:3306/vinsight?useSSL=false&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=fiap
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA / Hibernate ===
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# === Flyway ===
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# === Jackson (Jackson 3.x — datas já são ISO-8601 por default) ===
spring.jackson.time-zone=America/Sao_Paulo

# === SpringDoc / Swagger ===
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
